import { createOrders } from "#db/queries/orders";

export async function seedOrders() {
  const orders = [
  {
    customer_id: 1,
    total_amount: 1247.5,
    order_status: "shipped",
    assigned_service_rep: 8,
    created_date: "2025-09-15",
  },
  {
    customer_id: 1,
    total_amount: 890.25,
    order_status: "delivered",
    assigned_service_rep: 8,
    created_date: "2025-10-01",
  },
  {
    customer_id: 1,
    total_amount: 2340.0,
    order_status: "processing",
    assigned_service_rep: 9,
    created_date: "2025-11-02",
  },
  {
    customer_id: 2,
    total_amount: 456.89,
    order_status: "pending",
    assigned_service_rep: 8,
    created_date: "2025-11-01",
  },
  {
    customer_id: 3,
    total_amount: 3456.75,
    order_status: "delivered",
    assigned_service_rep: 10,
    created_date: "2025-08-20",
  },
  {
    customer_id: 3,
    total_amount: 1200.0,
    order_status: "shipped",
    assigned_service_rep: 10,
    created_date: "2025-09-10",
  },
  {
    customer_id: 3,
    total_amount: 675.5,
    order_status: "delivered",
    assigned_service_rep: 11,
    created_date: "2025-09-25",
  },
  {
    customer_id: 3,
    total_amount: 2100.25,
    order_status: "processing",
    assigned_service_rep: 10,
    created_date: "2025-10-15",
  },
  {
    customer_id: 3,
    total_amount: 890.0,
    order_status: "pending",
    assigned_service_rep: 11,
    created_date: "2025-11-03",
  },
  {
    customer_id: 5,
    total_amount: 145.99,
    order_status: "cancelled",
    assigned_service_rep: 9,
    created_date: "2025-09-05",
  },
  {
    customer_id: 5,
    total_amount: 320.5,
    order_status: "shipped",
    assigned_service_rep: 9,
    created_date: "2025-10-22",
  },
  {
    customer_id: 6,
    total_amount: 5600.0,
    order_status: "delivered",
    assigned_service_rep: 12,
    created_date: "2025-08-10",
  },
  {
    customer_id: 6,
    total_amount: 2340.75,
    order_status: "delivered",
    assigned_service_rep: 12,
    created_date: "2025-09-18",
  },
  {
    customer_id: 6,
    total_amount: 1890.25,
    order_status: "shipped",
    assigned_service_rep: 8,
    created_date: "2025-10-28",
  },
  {
    customer_id: 6,
    total_amount: 4200.0,
    order_status: "processing",
    assigned_service_rep: 12,
    created_date: "2025-11-04",
  },
  {
    customer_id: 8,
    total_amount: 78.5,
    order_status: "delivered",
    assigned_service_rep: 11,
    created_date: "2025-10-12",
  },
  {
    customer_id: 9,
    total_amount: 1567.25,
    order_status: "shipped",
    assigned_service_rep: 10,
    created_date: "2025-09-28",
  },
  {
    customer_id: 9,
    total_amount: 890.0,
    order_status: "processing",
    assigned_service_rep: 10,
    created_date: "2025-10-30",
  },
  {
    customer_id: 9,
    total_amount: 2345.75,
    order_status: "pending",
    assigned_service_rep: 9,
    created_date: "2025-11-03",
  },
  {
    customer_id: 10,
    total_amount: 450.0,
    order_status: "delivered",
    assigned_service_rep: 11,
    created_date: "2025-09-22",
  },
  {
    customer_id: 10,
    total_amount: 670.25,
    order_status: "shipped",
    assigned_service_rep: 11,
    created_date: "2025-10-25",
  },
  {
    customer_id: 12,
    total_amount: 234.99,
    order_status: "pending",
    assigned_service_rep: 12,
    created_date: "2025-11-01",
  },
  {
    customer_id: 13,
    total_amount: 1200.0,
    order_status: "delivered",
    assigned_service_rep: 8,
    created_date: "2025-08-15",
  },
  {
    customer_id: 13,
    total_amount: 3450.5,
    order_status: "delivered",
    assigned_service_rep: 9,
    created_date: "2025-09-12",
  },
  {
    customer_id: 13,
    total_amount: 890.25,
    order_status: "shipped",
    assigned_service_rep: 8,
    created_date: "2025-10-20",
  },
  {
    customer_id: 13,
    total_amount: 1567.0,
    order_status: "processing",
    assigned_service_rep: 9,
    created_date: "2025-11-02",
  },
  {
    customer_id: 14,
    total_amount: 567.75,
    order_status: "cancelled",
    assigned_service_rep: 10,
    created_date: "2025-09-30",
  },
  {
    customer_id: 14,
    total_amount: 1890.0,
    order_status: "pending",
    assigned_service_rep: 10,
    created_date: "2025-11-04",
  },
];
  for (const order of orders) {
      await createOrders(order);
    }
    console.log("completed seeding orders");
}
